module.exports = {
    authService: require('./auth.service'),
    emailService: require('./email.service'),
    tokenService: require('./token.service'),
    userService: require('./user.service'),
    subjectService: require('./subject.service'),
    classroomService: require('./classroom.service'),
    assignmentService: require('./assignment.service'),
    quizService: require('./quiz.service'),
    motivationQuoteService: require('./motivation_quote.service'),
    stateService: require('./state.service'),
    cityService: require('./city.service'),
    questionService: require('./question.service'),
    dashboardService: require('./dashboard.service'),
    branchService: require('./branch.service'),
};