module.exports = {
    Address: require('./address.model'),
    Assignment: require('./assignment.model'),
    City: require('./city.model'),
    Classroom: require('./classroom.model'),
    District: require('./state.model'),
    MotivationQuote: require('./motivation_quote.model'),
    Question: require('./question.model'),
    QuestionAnswer: require('./question_answer.model'),
    QuestionOption: require('./question_option.model'),
    QuestionType: require('./question_type.model'),
    Quiz: require('./quiz.model'),
    QuizMark: require('./quiz_mark.model'),
    Subject: require('./subject.model'),
    Token: require('./token.model'),
    User: require('./user.model'),
    State: require('./state.model'),
};