module.exports = {
    Address: require('./address.model'),
    Assignment: require('./assignment.model'),
    City: require('./city.model'),
    Classroom: require('./classroom.model'),
    MotivationQuote: require('./motivation_quote.model'),
    Question: require('./question.model'),
    Quiz: require('./quiz.model'),
    Subject: require('./subject.model'),
    Token: require('./token.model'),
    User: require('./user.model'),
    State: require('./state.model'),
    Option: require('./option.model'),
    Answer: require('./answer.model'),
    Mark: require('./mark.model'),
    Branch: require('./branch.model'),
    Package: require('./package.model'),
    Payment: require('./payment.model'),
};